# Generated by Django 5.1.5 on 2025-01-16 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=32, verbose_name='任务名')),
                ('add_time', models.DateField(blank=True, default='2025-01-16', null=True, verbose_name='添加时间')),
                ('ddl', models.DateTimeField(blank=True, null=True, verbose_name='DDL')),
                ('status', models.SmallIntegerField(choices=[(1, 'to do'), (2, 'finished')], default=1, verbose_name='状态')),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('total_time', models.IntegerField(blank=True, null=True, verbose_name='总用时')),
                ('count', models.IntegerField(default=1)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.todolist', verbose_name='任务名')),
            ],
        ),
    ]
