# Generated by Django 5.1.5 on 2025-01-16 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='job',
            field=models.CharField(max_length=64, verbose_name='任务名'),
        ),
        migrations.CreateModel(
            name='TimeRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_time', models.DateTimeField(blank=True, null=True, verbose_name='专注时间')),
                ('count', models.IntegerField(default=1)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='api.todolist', verbose_name='任务名')),
            ],
        ),
        migrations.DeleteModel(
            name='Records',
        ),
    ]
