# Generated by Django 5.1.5 on 2025-01-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todolist_job_timerecords_delete_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecords',
            name='focus_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='专注时间'),
        ),
    ]
