# Generated by Django 5.1.5 on 2025-01-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_timerecords_focus_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecords',
            name='count',
        ),
        migrations.RemoveField(
            model_name='timerecords',
            name='focus_time',
        ),
        migrations.AddField(
            model_name='timerecords',
            name='occur_time',
            field=models.DateField(blank=True, default='2025-01-16', null=True, verbose_name='发生时间'),
        ),
        migrations.AddField(
            model_name='timerecords',
            name='total_focus_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='总专注时间'),
        ),
    ]
