# Generated by Django 5.1.5 on 2025-01-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_timerecords_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecords',
            name='total_focus_time',
        ),
        migrations.AddField(
            model_name='timerecords',
            name='focus_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='专注时间'),
        ),
        migrations.AlterField(
            model_name='timerecords',
            name='occur_time',
            field=models.DateField(blank=True, default='2025-01-17', null=True, verbose_name='发生时间'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='add_time',
            field=models.DateField(blank=True, default='2025-01-17', null=True, verbose_name='添加时间'),
        ),
    ]
