# Generated by Django 5.1.5 on 2025-01-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_timerecords_total_focus_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'to do'), (1, 'finished')], default=0, verbose_name='状态'),
        ),
    ]
